spring:
    kafka:
        bootstrap-servers: 192.168.230.156:9092
        client-id: mykafka
        consumer:
            auto-commit-interval: 1000
            auto-offset-reset: latest
            enable-auto-commit: true
            group-id: myGroup
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            topic: my-replicated-topic,test
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        listener:
            concurrency: 3
        producer:
            batch-size: 1000
        template:
            default-topic: my-replicated-topic
