package com.feng.baseframework.mydrools

import com.feng.baseframework.model.User;

//drl文件的rule不能重复
rule "user rule1"
    salience 1
    no-loop true
    when
        matd : User(userName != null, userName.toUpperCase() == "ADMIN");
    then
        System.out.println("rule1,admin用户!");
        matd.addId("1");
        System.out.println(matd.getIds());
        System.out.println(matd);
        System.out.println(Thread.currentThread());
        //retract(matd);
end